# Generated by Django 4.1.4 on 2023-01-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='matieres_premieres',
        ),
        migrations.AddField(
            model_name='input',
            name='quantite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='quantite',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
