# Generated by Django 4.1.4 on 2023-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_input_matieres_premieres_input_quantite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mains_d_oeuvres',
            old_name='nombre_ou_quantite',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='input',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mains_d_oeuvres',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mains_d_oeuvres',
            name='revenu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
