# Generated by Django 4.1.4 on 2023-01-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nombre_ou_quantite_mains_d_oeuvres_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='stock',
            new_name='stock_id',
        ),
    ]
