# Generated by Django 4.1.4 on 2023-01-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_situation_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='produit_finis',
            new_name='produit',
        ),
        migrations.RemoveField(
            model_name='production',
            name='category',
        ),
        migrations.RemoveField(
            model_name='production',
            name='cout_production',
        ),
        migrations.RemoveField(
            model_name='production',
            name='quantite_produite',
        ),
        migrations.RemoveField(
            model_name='production',
            name='stock',
        ),
        migrations.AddField(
            model_name='mains_d_oeuvres',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.production'),
        ),
        migrations.AlterField(
            model_name='production',
            name='unite_production',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('unite_production', models.CharField(max_length=100)),
                ('cout_production_total', models.FloatField(blank=True, null=True)),
                ('cout_production_unitaire', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.production')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout_total_sorties', models.FloatField(blank=True, null=True)),
                ('cout_total_m', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.production')),
            ],
        ),
    ]
