# Generated by Django 4.1.4 on 2023-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_produit_finis_production_produit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='produit',
            new_name='nom_prod',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cout_production_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cout_production_unitaire',
        ),
        migrations.RemoveField(
            model_name='product',
            name='production',
        ),
        migrations.AddField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='produit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
