# Generated by Django 4.1.4 on 2023-01-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_produit_production_nom_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.production'),
        ),
    ]
