# Generated by Django 4.1.4 on 2023-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_output_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='categories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='stocks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
