# Generated by Django 4.1.4 on 2023-01-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_depense_categories_depense_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cout_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('unite', models.CharField(blank=True, max_length=45, null=True)),
                ('cout_total_pro', models.FloatField(blank=True, null=True)),
                ('cout_prod', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.depense')),
            ],
        ),
    ]
