# Generated by Django 4.1.4 on 2023-01-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cout_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cout_production',
            old_name='cout_prod',
            new_name='cout_de_production',
        ),
        migrations.RenameField(
            model_name='cout_production',
            old_name='cout_total_pro',
            new_name='cout_total_production',
        ),
        migrations.AddField(
            model_name='cout_production',
            name='quantite_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
