# Generated by Django 4.1.4 on 2023-01-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_cout_prod_cout_production_cout_de_production_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cout_production',
            old_name='cout_total_production',
            new_name='cout_total_pro',
        ),
    ]
