# Generated by Django 4.1.4 on 2023-02-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_premiere', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='depense',
            old_name='cout_total_m',
            new_name='Prix_total_depense',
        ),
        migrations.RenameField(
            model_name='depense',
            old_name='date',
            new_name='date_depense',
        ),
        migrations.RenameField(
            model_name='depense',
            old_name='cout_total_sorties',
            new_name='prix_unitaire_depense',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='quantite',
            new_name='prix_unitaire_entree',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='total',
            new_name='quantite_entree',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='quantite',
            new_name='priX_unitaire_sortie',
        ),
        migrations.RenameField(
            model_name='output',
            old_name='total',
            new_name='prix_total_sortie',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='produit',
            new_name='type_produit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='nom_categorie',
        ),
        migrations.RemoveField(
            model_name='category',
            name='revenu',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='stocks',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='type_depense',
        ),
        migrations.RemoveField(
            model_name='input',
            name='date',
        ),
        migrations.RemoveField(
            model_name='input',
            name='price',
        ),
        migrations.RemoveField(
            model_name='input',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='mains_d_oeuvres',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mains_d_oeuvres',
            name='production',
        ),
        migrations.RemoveField(
            model_name='output',
            name='date',
        ),
        migrations.RemoveField(
            model_name='output',
            name='price',
        ),
        migrations.RemoveField(
            model_name='output',
            name='production',
        ),
        migrations.RemoveField(
            model_name='output',
            name='stock_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unite_production',
        ),
        migrations.RemoveField(
            model_name='production',
            name='date',
        ),
        migrations.RemoveField(
            model_name='production',
            name='nom_prod',
        ),
        migrations.AddField(
            model_name='category',
            name='type_depense',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie_depense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AddField(
            model_name='depense',
            name='quantite_depense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='unite_entree',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='matiere_premiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.input'),
        ),
        migrations.AddField(
            model_name='output',
            name='quantite_sortie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='quantite_stock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='unite_sortie',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='cout_production',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='date_production',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='produit_fini',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='production',
            name='quantite_produite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='utilisateur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='unite_production',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='matiere_Premiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.matierepremiere'),
        ),
    ]
