# Generated by Django 4.1.4 on 2023-02-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_matierepremiere_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='entrees',
            new_name='entree',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sorties',
            new_name='sortie',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='matieres_premieres',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unite_entrees_sorties',
        ),
        migrations.AddField(
            model_name='stock',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='matiere_premiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.output'),
        ),
        migrations.AddField(
            model_name='stock',
            name='unite_entree_sortie',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
