# Generated by Django 4.1.4 on 2023-02-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_entrees_stock_entree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='matiere_premiere',
            new_name='matierePremiere',
        ),
    ]
