# Generated by Django 4.1.4 on 2023-02-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_matierepremiere_stock_matiere_premieres'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='date_entree',
            field=models.DateField(blank=True, null=True),
        ),
    ]
