# Generated by Django 4.1.4 on 2023-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_output_date_entree'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='date_production',
            field=models.DateField(blank=True, null=True),
        ),
    ]
