# Generated by Django 4.1.4 on 2023-02-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_depense_date_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='date_production',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.production'),
        ),
    ]
