# Generated by Django 4.1.4 on 2023-02-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_output_date_production_output_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produite', models.FloatField(blank=True, null=True)),
                ('stock_mp', models.FloatField(blank=True, null=True)),
                ('cout_total_sortie', models.FloatField(blank=True, null=True)),
                ('type_depense', models.DateField(blank=True, null=True)),
                ('cout_total_depense', models.DateField(blank=True, null=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.production')),
            ],
        ),
    ]
