# Generated by Django 4.1.4 on 2023-02-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_cout_type_depense_remove_output_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cout',
            name='cout_production',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cout',
            name='cout_total_production',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
