# Generated by Django 4.1.4 on 2023-02-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_cout_type_depense_remove_output_date_entree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cout',
            name='quantite_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
