# Generated by Django 4.1.4 on 2023-02-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_cout_type_depense_remove_output_date_entree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produite', models.FloatField(blank=True, null=True)),
                ('cout_total_production', models.FloatField(blank=True, null=True)),
                ('quantite_total', models.FloatField(blank=True, null=True)),
                ('cout_production', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cout_production',
        ),
        migrations.DeleteModel(
            name='Situation_stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='calcul',
            name='cout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cout'),
        ),
    ]
