# Generated by Django 4.1.4 on 2023-02-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_calcul_remove_cout_production_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mains_d_oeuvres',
        ),
        migrations.RenameField(
            model_name='calcul',
            old_name='cout_total_production',
            new_name='cout_production_total',
        ),
        migrations.RenameField(
            model_name='calcul',
            old_name='quantite_produite',
            new_name='quantiteProduite',
        ),
    ]
