from .home import *
from .categories import *
from .matierePremieres import *
from .inputs import *
from .outputs import *
from .productions import *
from .depenses import *
from .products import *
from .users import *
from .home_gest import *
from .home_resp import *
from .categories_resp import *
from .input_admin import *
from .output_admin import *
from .product_admin import *
from .production_admin import *
from .depense_admin import *
from .couts import *